### ISSUE TITLE
FBX error

### ISSUE THREAD

**Issue by Libaier** [keijiro/CMUMocap#2]
The project works well by using 135_01.fbx(or any other fbx files in ''CMUMocap''), 

But when I import other fbx files(http://www.thetrailerspark.com/download/Mocap/Singles/CMU/Library/FBX/), It fail to get the desired  animation result.

Is there any other processes that I need to do before I import the fbx files?

**Comment by keijiro** [comment]
Sorry I have no idea about what they made. I spent much time to cleaning up the mocap data and adapting it to Unity. Probably their data is not processed well.

**Comment by Libaier** [comment]
Can your tell me how to cleaning up those data briefly?
It seems that there's no noise in the data.
Sorry I have no idea about this problem...

**Comment by keijiro** [comment]
I've done things like this again and again...

https://twitter.com/_kzr/status/805326049642889216
https://twitter.com/_kzr/status/812204191930195968
https://twitter.com/_kzr/status/810385833408733184

**Comment by Libaier** [comment]
Thanks a lot~

**Comment by Libaier** [comment]
https://www.assetstore.unity3d.com/cn/#!/content/19991
Maybe this plugin can help you solve this problem

**Comment by keijiro** [comment]
What is the problem? I have no problem with my dataset :)

**Comment by Libaier** [comment]
Sorry, it's my problem
